import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
=======
import { Alexandria } from "next/font/google";
import Providers from "@/components/PrivyConnection";
import Navbar from "@/components/Navbar";
import "./globals.css";

const alexandria = Alexandria({
  variable: "--font-alexandria",
>>>>>>> d589705abaad460e6743e45691adb8f1e736e6fa
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
      <body className={`${alexandria.variable} antialiased bg-background`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
>>>>>>> d589705abaad460e6743e45691adb8f1e736e6fa
      </body>
    </html>
  );
}
